import fs from 'node:fs';

function replaceOnce(source, before, after, label) {
  if (source.includes(after)) return source;
  if (!source.includes(before)) throw new Error(`patch-v6: trecho não encontrado: ${label}`);
  return source.replace(before, after);
}

const appPath = new URL('../src/AppNoAuthV3.tsx', import.meta.url);
let app = fs.readFileSync(appPath, 'utf8');

app = replaceOnce(app, "import { BillingPanel, DashboardMap, EquipmentPanel } from './AgendaEnhancements';", "import { BillingPanel, DashboardMap, EquipmentPanel } from './AgendaEnhancements';\nimport { DashboardMapV2 } from './MapPanelV2';\nimport { ContactUpdatesPanel } from './ContactUpdatesPanel';", 'imports extras');
app = replaceOnce(app, "type View = 'dashboard' | 'agenda' | 'outras' | 'equipamentos' | 'faturamento' | 'retencao' | 'caretrack';", "type View = 'dashboard' | 'agenda' | 'outras' | 'equipamentos' | 'faturamento' | 'retencao' | 'acompanhamentos' | 'caretrack';", 'view acompanhamentos');
app = replaceOnce(app, "  if (view === 'retencao') return 'Retenção';\n  return 'CareTrack';", "  if (view === 'retencao') return 'Retenção';\n  if (view === 'acompanhamentos') return 'Acompanhamentos';\n  return 'CareTrack';", 'view title');
app = replaceOnce(app, "supabase.from('branches').select('id,name,slug').eq('active', true).order('name')", "supabase.from('branches').select('id,name,slug,address,city,state,postal_code').eq('active', true).order('name')", 'branch address select');
app = replaceOnce(app, "supabase.from('user_branches').select('branches(id,name,slug)').eq('user_id', currentProfile.id)", "supabase.from('user_branches').select('branches(id,name,slug,address,city,state,postal_code)').eq('user_id', currentProfile.id)", 'allowed branch address select');
app = replaceOnce(app, "<DashboardMap appointments={appointments} branches={allBranches} scopeLabel={selectedScopeLabel} />", "<DashboardMapV2 appointments={appointments} branches={ownBranches} scopeLabel={selectedScopeLabel} />", 'map v2');
app = replaceOnce(app, "        <Nav active={view === 'retencao'} icon={<ClipboardCheck />} label='Retenção' onClick={() => setView('retencao')} />\n        <Nav active={view === 'caretrack'} icon={<Gauge />} label='CareTrack' onClick={() => setView('caretrack')} />", "        <Nav active={view === 'retencao'} icon={<ClipboardCheck />} label='Retenção' onClick={() => setView('retencao')} />\n        <Nav active={view === 'acompanhamentos'} icon={<CalendarDays />} label='Acompanhamentos' onClick={() => setView('acompanhamentos')} />\n        <Nav active={view === 'caretrack'} icon={<Gauge />} label='CareTrack' onClick={() => setView('caretrack')} />", 'nav acompanhamentos');
app = replaceOnce(app, "{view === 'retencao' && <RetentionPanel profileId={profile.id} branchNames={selectedBranchIds.map((id) => allBranches.find((branch) => branch.id === id)?.name).filter(Boolean) as string[]} allBranchCount={allBranches.length} canEdit={Boolean(baseCanEdit)} scopeLabel={selectedScopeLabel} />}\n        {view === 'caretrack'", "{view === 'retencao' && <RetentionPanel profileId={profile.id} branchNames={selectedBranchIds.map((id) => allBranches.find((branch) => branch.id === id)?.name).filter(Boolean) as string[]} allBranchCount={allBranches.length} canEdit={Boolean(baseCanEdit)} scopeLabel={selectedScopeLabel} />}\n        {view === 'acompanhamentos' && <ContactUpdatesPanel profile={profile} branchNames={selectedBranchIds.map((id) => allBranches.find((branch) => branch.id === id)?.name).filter(Boolean) as string[]} allBranchCount={allBranches.length} canEdit={Boolean(baseCanEdit)} scopeLabel={selectedScopeLabel} />}\n        {view === 'caretrack'", 'render acompanhamentos');
app = replaceOnce(app, "view === 'caretrack' ? 'Atualize o último serviço sem alterar os dados automáticos.' : view === 'faturamento' ?", "view === 'caretrack' ? 'Atualize o último serviço sem alterar os dados automáticos.' : view === 'acompanhamentos' ? 'Histórico de contatos, visitas, responsáveis, retornos e funil de serviços.' : view === 'faturamento' ?", 'guidance acompanhamentos');
fs.writeFileSync(appPath, app);

const operationsPath = new URL('../src/OperationsPanels.tsx', import.meta.url);
let operations = fs.readFileSync(operationsPath, 'utf8');
operations = replaceOnce(operations, "export function RetentionPanel({ profileId, branchNames, canEdit, scopeLabel }: Props) {", "export function RetentionPanel({ profileId, branchNames, allBranchCount, canEdit, scopeLabel }: Props) {", 'retention all branch count');
operations = replaceOnce(operations, "  const [typeFilter, setTypeFilter] = useState('todos');\n  const [sortMode, setSortMode] = useState('antigos');", "  const [typeFilter, setTypeFilter] = useState('todos');\n  const [branchFilter, setBranchFilter] = useState('todas');\n  const [sortMode, setSortMode] = useState('antigos');", 'retention branch state');
operations = replaceOnce(operations, "      const typeMatch = typeFilter === 'todos' || row.last_treatment_type === typeFilter;\n      const branchMatch = branchNames.length === 0 || branchNames.some((branch) => normalizeKey(branch) === normalizeKey(row.branch));\n      return textMatch && agingMatch && statusMatch && typeMatch && branchMatch;", "      const typeMatch = typeFilter === 'todos' || row.last_treatment_type === typeFilter;\n      const allowedScope = branchNames.length === 0 || branchNames.length >= allBranchCount || branchNames.some((branch) => normalizeKey(branch) === normalizeKey(row.branch));\n      const branchMatch = branchFilter === 'todas' || normalizeKey(row.branch) === normalizeKey(branchFilter);\n      return textMatch && agingMatch && statusMatch && typeMatch && allowedScope && branchMatch;", 'retention scope filter');
operations = replaceOnce(operations, "  }, [rows, query, agingFilter, statusFilter, typeFilter, sortMode, branchNames]);", "  }, [rows, query, agingFilter, statusFilter, typeFilter, branchFilter, sortMode, branchNames, allBranchCount]);", 'retention filter deps');
operations = replaceOnce(operations, "      <div className='inline-search'><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder='Cliente, cidade, série ou contato' /></div>\n      <select value={agingFilter}", "      <div className='inline-search'><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder='Cliente, cidade, série ou contato' /></div>\n      <select value={branchFilter} onChange={(event) => setBranchFilter(event.target.value)}><option value='todas'>Todas as filiais</option>{branchNames.map((branch) => <option key={branch} value={branch}>{branch}</option>)}</select>\n      <select value={agingFilter}", 'retention branch select');
operations = replaceOnce(operations, "      notes: draft.notes.trim() || null,\n      created_by: profileId,", "      notes: draft.notes.trim() || null,\n      activity_date: new Date().toISOString().slice(0, 10),\n      responsible_user_id: profileId,\n      created_by: profileId,", 'retention responsible');
fs.writeFileSync(operationsPath, operations);
console.log('patch-v6 aplicado');
