import { useCallback, useEffect, useMemo, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, ClipboardCheck, Gauge, LayoutDashboard, LogOut, Plus, Search, Truck, UserRound, WalletCards, X } from 'lucide-react';
import { supabase } from './lib/supabase';
import type { Appointment, AppointmentStatus, Branch, Equipment, Profile, Technician } from './types';

type View = 'dashboard' | 'agenda' | 'equipamentos' | 'faturamento' | 'retencao' | 'caretrack';
type QuickDraft = { id?: string; date: string; technicianId: string; statusId: string; amount: string; notes: string };
const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const shortDate = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit' });
const longDate = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' });
const weekday = new Intl.DateTimeFormat('pt-BR', { weekday: 'short' });
function isoDate(date: Date) { const y = date.getFullYear(); const m = String(date.getMonth()+1).padStart(2,'0'); const d = String(date.getDate()).padStart(2,'0'); return `${y}-${m}-${d}`; }
function startOfWeek(input: Date) { const date = new Date(input); const day = date.getDay(); const diff = day === 0 ? -6 : 1-day; date.setDate(date.getDate()+diff); date.setHours(0,0,0,0); return date; }
function addDays(input: Date, amount: number) { const date = new Date(input); date.setDate(date.getDate()+amount); return date; }
function roleLabel(role: Profile['role']) { return role === 'admin' ? 'Administrador' : role === 'gestor' ? 'Gestor' : 'Consultor'; }
function viewTitle(view: View) { return view === 'dashboard' ? 'Visão geral' : view === 'agenda' ? 'Agenda semanal' : view === 'equipamentos' ? 'Equipamentos' : view === 'faturamento' ? 'Faturamento' : view === 'retencao' ? 'Retenção' : 'CareTrack'; }

export default function AppNoAuth() {
  const [profile,setProfile] = useState<Profile|null>(null);
  const [matricula,setMatricula] = useState(() => localStorage.getItem('agenda_matricula') || '');
  const [entering,setEntering] = useState(false);
  const [entryError,setEntryError] = useState('');
  const [branches,setBranches] = useState<Branch[]>([]);
  const [branchId,setBranchId] = useState('');
  const [statuses,setStatuses] = useState<AppointmentStatus[]>([]);
  const [technicians,setTechnicians] = useState<Technician[]>([]);
  const [appointments,setAppointments] = useState<Appointment[]>([]);
  const [weekStart,setWeekStart] = useState(() => startOfWeek(new Date()));
  const [view,setView] = useState<View>('dashboard');
  const [loadingData,setLoadingData] = useState(false);
  const [draft,setDraft] = useState<QuickDraft|null>(null);
  const [saveError,setSaveError] = useState('');
  const [newTechName,setNewTechName] = useState('');
  const [showNewTech,setShowNewTech] = useState(false);
  const [equipmentQuery,setEquipmentQuery] = useState('');
  const [equipmentResults,setEquipmentResults] = useState<Equipment[]>([]);
  const [equipmentLoading,setEquipmentLoading] = useState(false);

  const enterByMatricula = useCallback(async (raw: string, silent=false) => {
    const clean = raw.replace(/\D/g,''); if (!clean) return; if (!silent) setEntering(true); setEntryError('');
    const {data:userData,error:userError} = await supabase.from('app_users').select('id,matricula,full_name,role').eq('matricula',clean).eq('active',true).maybeSingle();
    if (userError || !userData) { localStorage.removeItem('agenda_matricula'); setProfile(null); setEntryError('Matrícula não encontrada.'); setEntering(false); return; }
    const currentProfile = userData as Profile;
    const {data:statusData} = await supabase.from('appointment_statuses').select('id,name,color_hex,text_color,sort_order').eq('active',true).order('sort_order');
    setStatuses((statusData || []) as AppointmentStatus[]);
    let allowed: Branch[] = [];
    if (currentProfile.role === 'consultor') {
      const {data:accessData} = await supabase.from('user_branches').select('branches(id,name,slug)').eq('user_id',currentProfile.id);
      allowed = (accessData || []).map((item:any)=>item.branches).filter(Boolean) as Branch[];
    } else {
      const {data:branchData} = await supabase.from('branches').select('id,name,slug').eq('active',true).order('name'); allowed = (branchData || []) as Branch[];
    }
    setProfile(currentProfile); setBranches(allowed); setBranchId(allowed[0]?.id || ''); localStorage.setItem('agenda_matricula',clean); setEntering(false);
  },[]);
  useEffect(() => { const saved = localStorage.getItem('agenda_matricula'); if (saved) enterByMatricula(saved,true); },[enterByMatricula]);

  const weekDays = useMemo(() => Array.from({length:6},(_,i)=>addDays(weekStart,i)),[weekStart]);
  const weekEnd = weekDays[5]; const currentBranch = branches.find(b=>b.id===branchId) || null; const canEdit = profile?.role === 'consultor' || profile?.role === 'admin'; const todayIso = isoDate(new Date());
  const loadAgenda = useCallback(async () => {
    if (!branchId || !profile) return; setLoadingData(true); const from=isoDate(weekStart), to=isoDate(weekEnd);
    const [techResponse,appointmentResponse] = await Promise.all([
      supabase.from('technicians').select('id,branch_id,name,source').eq('branch_id',branchId).eq('active',true).order('name'),
      supabase.from('appointments').select('id,branch_id,appointment_date,technician_id,technician_name_manual,status_id,amount,notes,billing_status,invoice_number,status:appointment_statuses(id,name,color_hex,text_color,sort_order),technician:technicians(id,name)').eq('branch_id',branchId).is('deleted_at',null).gte('appointment_date',from).lte('appointment_date',to).order('appointment_date')
    ]);
    setTechnicians((techResponse.data || []) as Technician[]); setAppointments((appointmentResponse.data || []) as unknown as Appointment[]); setLoadingData(false);
  },[branchId,profile,weekStart,weekEnd]);
  useEffect(()=>{loadAgenda();},[loadAgenda]);

  function leaveProfile(){ localStorage.removeItem('agenda_matricula'); setProfile(null); setBranches([]); setBranchId(''); setAppointments([]); setMatricula(''); setView('dashboard'); }
  function openNew(date:string,technicianId:string){ if(!canEdit)return; setSaveError(''); setDraft({date,technicianId,statusId:statuses[0]?.id||'',amount:'',notes:''}); }
  function openEdit(item:Appointment){ if(!canEdit)return; setSaveError(''); setDraft({id:item.id,date:item.appointment_date,technicianId:item.technician_id||'',statusId:item.status_id,amount:item.amount?String(item.amount):'',notes:item.notes||''}); }
  async function saveAppointment(event:FormEvent){ event.preventDefault(); if(!draft||!profile||!branchId)return; if(!draft.date||!draft.technicianId||!draft.statusId){setSaveError('Preencha data, técnico e status.');return;} const payload={branch_id:branchId,appointment_date:draft.date,technician_id:draft.technicianId,technician_name_manual:null,status_id:draft.statusId,amount:Number(String(draft.amount||'0').replace(',','.'))||0,notes:draft.notes.trim()||null,updated_by:profile.id}; const response=draft.id?await supabase.from('appointments').update(payload).eq('id',draft.id):await supabase.from('appointments').insert({...payload,created_by:profile.id}); if(response.error){setSaveError(response.error.message);return;} setDraft(null); await loadAgenda(); }
  async function removeAppointment(){ if(!draft?.id||!profile||!canEdit)return; const {error}=await supabase.from('appointments').update({deleted_at:new Date().toISOString(),updated_by:profile.id}).eq('id',draft.id); if(error){setSaveError(error.message);return;} setDraft(null); await loadAgenda(); }
  async function addTechnician(event:FormEvent){ event.preventDefault(); const name=newTechName.trim(); if(!name||!branchId||!canEdit)return; const {error}=await supabase.from('technicians').insert({branch_id:branchId,name,source:'adhoc'}); if(error){setSaveError(error.message.includes('duplicate')?'Esse técnico já está cadastrado nesta filial.':error.message);return;} setNewTechName(''); setShowNewTech(false); await loadAgenda(); }
  async function searchEquipment(event:FormEvent){ event.preventDefault(); const query=equipmentQuery.trim(); if(!query||!branchId)return; setEquipmentLoading(true); const {data}=await supabase.from('equipment').select('id,serial,manufacturer,model,city,state,current_hourmeter,hourmeter_date,caretrack_status,client:clients(name)').eq('branch_id',branchId).ilike('serial',`%${query}%`).limit(20); setEquipmentResults((data||[]) as unknown as Equipment[]); setEquipmentLoading(false); }
  async function updateBilling(item:Appointment,value:string){ if(!profile||!canEdit)return; await supabase.from('appointments').update({billing_status:value,updated_by:profile.id}).eq('id',item.id); await loadAgenda(); }

  if(!profile) return <div className='matricula-screen'><form className='matricula-card' onSubmit={e=>{e.preventDefault();enterByMatricula(matricula);}}><div className='matricula-icon'><UserRound/></div><h1>Agenda de Atendimentos</h1><p>Digite somente sua matrícula para entrar.</p><label>Matrícula<input autoFocus inputMode='numeric' value={matricula} onChange={e=>setMatricula(e.target.value.replace(/\D/g,''))} placeholder='Ex.: 19124'/></label>{entryError&&<div className='form-error'>{entryError}</div>}<button className='primary-button' disabled={entering||!matricula.trim()}>{entering?'Entrando...':'Entrar'}</button><small>Projeto interno · sem senha</small></form></div>;

  const todayAppointments=appointments.filter(i=>i.appointment_date===todayIso); const weeklyAmount=appointments.reduce((s,i)=>s+Number(i.amount||0),0); const activeTechCount=new Set(appointments.map(i=>i.technician_id).filter(Boolean)).size; const noAgenda=statuses.find(s=>s.name==='Sem agenda'); const noAgendaCount=noAgenda?appointments.filter(i=>i.status_id===noAgenda.id).length:0;
  return <div className='internal-app'>
    <aside className='internal-sidebar'><div className='internal-brand'><div className='brand-square'><CalendarDays/></div><div><strong>Agenda</strong><span>Atendimentos</span></div></div><nav><Nav active={view==='dashboard'} icon={<LayoutDashboard/>} label='Visão geral' onClick={()=>setView('dashboard')}/><Nav active={view==='agenda'} icon={<CalendarDays/>} label='Agenda' onClick={()=>setView('agenda')}/><Nav active={view==='equipamentos'} icon={<Truck/>} label='Equipamentos' onClick={()=>setView('equipamentos')}/><Nav active={view==='faturamento'} icon={<WalletCards/>} label='Faturamento' onClick={()=>setView('faturamento')}/><div className='nav-section'>CONTROLES</div><Nav active={view==='retencao'} icon={<ClipboardCheck/>} label='Retenção' onClick={()=>setView('retencao')}/><Nav active={view==='caretrack'} icon={<Gauge/>} label='CareTrack' onClick={()=>setView('caretrack')}/></nav><div className='user-block'><div className='user-avatar'>{profile.full_name.charAt(0)}</div><div><strong>{profile.full_name}</strong><span>{profile.matricula} · {roleLabel(profile.role)}</span></div><button title='Trocar matrícula' onClick={leaveProfile}><LogOut/></button></div></aside>
    <main className='internal-main'><header className='internal-topbar'><div><h1>{viewTitle(view)}</h1><p>{view==='agenda'?'Clique na célula, preencha e salve.':'Controle rápido por filial.'}</p></div><div className='topbar-right'><label>Filial<select value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><span className='profile-badge'>{roleLabel(profile.role)}</span></div></header>
      <div className='internal-content'>
        {view==='dashboard'&&<><div className='summary-grid'><Summary label='Hoje' value={String(todayAppointments.length)} detail='atendimentos'/><Summary label='Técnicos na semana' value={String(activeTechCount)} detail='com apontamento'/><Summary label='Sem agenda' value={String(noAgendaCount)} detail='na semana'/><Summary label='Valor da semana' value={brl.format(weeklyAmount)} detail='previsto'/></div><section className='clean-panel'><div className='panel-heading'><div><h2>Hoje · {currentBranch?.name||''}</h2><p>Resumo operacional do dia</p></div><button className='link-button' onClick={()=>setView('agenda')}>Abrir agenda</button></div>{todayAppointments.length===0?<Empty text='Nenhum atendimento apontado para hoje.'/>:<div>{todayAppointments.map(item=><AppointmentLine key={item.id} item={item} onClick={()=>openEdit(item)}/>)}</div>}</section><section className='clean-panel compact-status-panel'><div className='panel-heading'><div><h2>Cores de atendimento</h2><p>Padrão utilizado na agenda</p></div></div><div className='status-legend'>{statuses.map(s=><span key={s.id}><i style={{background:s.color_hex}}/>{s.name}</span>)}</div></section></>}
        {view==='agenda'&&<section className='clean-panel agenda-panel'><div className='agenda-toolbar'><div><h2>{currentBranch?.name||'Filial'}</h2><p>{longDate.format(weekStart)} — {longDate.format(weekEnd)}</p></div><div className='agenda-actions'>{canEdit&&<button className='secondary-button' onClick={()=>setShowNewTech(true)}><Plus/> Técnico adicional</button>}<button onClick={()=>setWeekStart(startOfWeek(new Date()))}>Hoje</button><button aria-label='Semana anterior' onClick={()=>setWeekStart(addDays(weekStart,-7))}><ChevronLeft/></button><button aria-label='Próxima semana' onClick={()=>setWeekStart(addDays(weekStart,7))}><ChevronRight/></button></div></div><div className='agenda-hint'>{canEdit?'Clique em qualquer espaço da grade para apontar.':'Gestor: visualização somente leitura.'}</div><div className='sheet-wrap'><div className='sheet-grid sheet-head'><div className='tech-head'>Técnico</div>{weekDays.map(day=><div key={isoDate(day)}><strong>{weekday.format(day).replace('.','')}</strong><span>{shortDate.format(day)}</span></div>)}</div>{loadingData?<div className='sheet-loading'>Carregando agenda...</div>:technicians.length===0?<Empty text='Nenhum técnico cadastrado nesta filial. Use “Técnico adicional”.'/>:technicians.map(tech=><div className='sheet-grid sheet-row' key={tech.id}><div className='tech-name'><strong>{tech.name}</strong>{tech.source==='adhoc'&&<span>adicional</span>}</div>{weekDays.map(day=>{const date=isoDate(day);const items=appointments.filter(i=>i.technician_id===tech.id&&i.appointment_date===date);return <div className={`sheet-cell ${canEdit?'clickable':''}`} key={date} onClick={()=>items.length===0&&openNew(date,tech.id)}>{items.length===0&&canEdit&&<span className='cell-plus'>+</span>}{items.map(item=><button key={item.id} className='appointment-chip' onClick={e=>{e.stopPropagation();openEdit(item);}} style={{background:item.status?.color_hex||'#64748b',color:item.status?.text_color||'#fff'}}><strong>{item.status?.name||'Atendimento'}</strong>{Number(item.amount||0)>0&&<span>{brl.format(Number(item.amount))}</span>}</button>)}</div>})}</div>)}</div></section>}
        {view==='equipamentos'&&<section className='clean-panel'><div className='panel-heading'><div><h2>Consulta por série</h2><p>Digite a série e o sistema busca os dados do equipamento.</p></div></div><form className='equipment-search' onSubmit={searchEquipment}><Search/><input value={equipmentQuery} onChange={e=>setEquipmentQuery(e.target.value)} placeholder='Número de série'/><button className='primary-button'>Buscar</button></form>{equipmentLoading?<Empty text='Buscando...'/>:equipmentResults.length===0?<Empty text={equipmentQuery?'Nenhum equipamento encontrado.':'Digite uma série para consultar.'}/>:<div className='equipment-table'>{equipmentResults.map(item=><div className='equipment-row' key={item.id}><div><strong>{item.serial}</strong><span>{item.client?.name||'Cliente não informado'}</span></div><div><span>Modelo</span><strong>{item.model||'—'}</strong></div><div><span>Cidade</span><strong>{[item.city,item.state].filter(Boolean).join(' - ')||'—'}</strong></div><div><span>Horímetro</span><strong>{item.current_hourmeter??'—'}</strong></div><div><span>CareTrack</span><strong>{item.caretrack_status||'—'}</strong></div></div>)}</div>}</section>}
        {view==='faturamento'&&<section className='clean-panel'><div className='panel-heading'><div><h2>Faturamento da semana</h2><p>Atualize o status sem sair da tela.</p></div></div>{appointments.length===0?<Empty text='Nenhum atendimento na semana selecionada.'/>:<div className='billing-list'>{appointments.map(item=><div className='billing-row' key={item.id}><div><strong>{item.technician?.name||'Técnico'}</strong><span>{shortDate.format(new Date(`${item.appointment_date}T12:00:00`))} · {item.status?.name||''}</span></div><strong>{brl.format(Number(item.amount||0))}</strong><select disabled={!canEdit} value={item.billing_status} onChange={e=>updateBilling(item,e.target.value)}><option value='nao_precificado'>Não precificado</option><option value='precificado'>Precificado</option><option value='aguardando_faturamento'>Aguardando faturamento</option><option value='faturado'>Faturado</option><option value='perdido'>Perdido</option></select></div>)}</div>}</section>}
        {view==='retencao'&&<ModulePlaceholder title='Retenção' text='Aqui ficará o fluxo de contato, retorno do cliente, retenção e motivo de perda.'/>}{view==='caretrack'&&<ModulePlaceholder title='CareTrack' text='Aqui ficará o histórico de verificação, alertas e ações por equipamento.'/>}
      </div>
    </main>
    {draft&&<div className='modal-layer' onMouseDown={()=>setDraft(null)}><form className='quick-modal' onSubmit={saveAppointment} onMouseDown={e=>e.stopPropagation()}><div className='quick-modal-head'><div><h2>{draft.id?'Editar apontamento':'Novo apontamento'}</h2><p>Preenchimento rápido, estilo planilha.</p></div><button type='button' onClick={()=>setDraft(null)}><X/></button></div><div className='quick-form'><label>Data<input type='date' value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Técnico<select value={draft.technicianId} onChange={e=>setDraft({...draft,technicianId:e.target.value})}>{technicians.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className='full-field'>Status<select value={draft.statusId} onChange={e=>setDraft({...draft,statusId:e.target.value})}>{statuses.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Valor<input inputMode='decimal' value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})} placeholder='0,00'/></label><label>Observação<input value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder='Opcional'/></label></div>{saveError&&<div className='form-error modal-error'>{saveError}</div>}<div className='quick-actions'>{draft.id&&<button type='button' className='danger-button' onClick={removeAppointment}>Excluir</button>}<span/><button type='button' className='secondary-button' onClick={()=>setDraft(null)}>Cancelar</button><button className='primary-button'>Salvar</button></div></form></div>}
    {showNewTech&&<div className='modal-layer' onMouseDown={()=>setShowNewTech(false)}><form className='small-modal' onSubmit={addTechnician} onMouseDown={e=>e.stopPropagation()}><div className='quick-modal-head'><div><h2>Técnico adicional</h2><p>Somente o nome. Nada além disso.</p></div><button type='button' onClick={()=>setShowNewTech(false)}><X/></button></div><label>Nome<input autoFocus value={newTechName} onChange={e=>setNewTechName(e.target.value)} placeholder='Nome do técnico'/></label><div className='quick-actions'><span/><span/><button type='button' className='secondary-button' onClick={()=>setShowNewTech(false)}>Cancelar</button><button className='primary-button'>Adicionar</button></div></form></div>}
  </div>;
}
function Nav({active,icon,label,onClick}:{active:boolean;icon:ReactNode;label:string;onClick:()=>void}){return <button className={`side-link ${active?'active':''}`} onClick={onClick}>{icon}<span>{label}</span></button>}
function Summary({label,value,detail}:{label:string;value:string;detail:string}){return <div className='summary-card'><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function AppointmentLine({item,onClick}:{item:Appointment;onClick:()=>void}){return <button className='today-row' onClick={onClick}><i style={{background:item.status?.color_hex||'#64748b'}}/><div><strong>{item.technician?.name||'Técnico'}</strong><span>{item.status?.name||'Atendimento'}</span></div><b>{Number(item.amount||0)>0?brl.format(Number(item.amount)):'—'}</b></button>}
function Empty({text}:{text:string}){return <div className='empty-state'>{text}</div>}
function ModulePlaceholder({title,text}:{title:string;text:string}){return <section className='clean-panel module-placeholder'><div className='module-icon'><ClipboardCheck/></div><h2>{title}</h2><p>{text}</p><span>Estrutura pronta para a próxima etapa.</span></section>}
